export const ADD_APPOINTMENT =  'ADD_APPOINTMENT';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';
export const EDIT_APPOINTMENT = 'EDIT_APPOINTMENT';

export const SET_GLOBAL_CITY = 'SET_GLOBAL_CITY';
export const OPEN_DAY = 'OPEN_DAY';
export const OPEN_LIST = 'OPEN_LIST';
export const CLOSE_DAY = 'CLOSE_DAY';
